{% set name = "nbappinator" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nbappinator-{{ version }}.tar.gz
  sha256: fd4857bf5b0f30c71d0a1102609c96641a6006f6be446892f79afc11cd93dfe8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11,<4.0
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >=3.11.0,<4.0.0
    - plotly >=5.22.0,<6.0.0
    - ipywidgets >=8.1.3,<9.0.0
    - ipyvuetify >=1.9.4,<2.0.0
    - ipyaggrid >=0.5.4,<0.6.0
    - ipytree >=0.2.2,<0.3.0
    - pandas >=2.2.2,<3.0.0

test:
  imports:
    - nbappinator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iqmo-org/nbappinator
  dev_url: https://github.com/iqmo-org/nbappinator
  summary: Jupyter Notebook Application Builder
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - paultiq
