{% set name = "nbappinator" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nbappinator-{{ version }}.tar.gz
  sha256: dc9d3822d7e99f103958d01ddaff12c728f5c1893be9f4878d8858c6e0f8eec5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7
    - ipywidgets >=7.8.0,<8.0
    - plotly
    - ipyvuetify >=1.9
    - ipyaggrid
    - ipytree
    - pandas >=1.5.3

test:
  imports:
    - nbappinator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iqmo-org/nbappinator
  dev_url: https://github.com/iqmo-org/nbappinator
  summary: Jupyter Notebook Application Builder
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - paultiq
