{% set name = "nbappinator" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nbappinator-{{ version }}.tar.gz
  sha256: 9923534790b07d68c6d2c78e86ec3613ccd3f193dd5dc5cb975051d1504c3917

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11,<4.0
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - anywidget >=0.9.21
    - traitlets >=5.0
    - python >=3.11.0,<4.0.0
    - plotly >=5.22.0,<6.0.0
    - ipywidgets >=8.1.8
    - ipyvuetify >=1.9.4,<2.0.0
    - ipyaggrid >=0.5.4,<0.6.0
    - ipytree >=0.2.2,<0.3.0
    - pandas >=2.2.2,<3.0.0

test:
  imports:
    - nbappinator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iqmo-org/nbappinator
  dev_url: https://github.com/iqmo-org/nbappinator
  summary: Jupyter Notebook Application Builder
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - paultiq
